query Categories($slug: String) {
  categories(filters: { slug: { eq: $slug } }) {
    data {
      id
      attributes {
        name
        slug
        articles {
          data {
            id
            attributes {
              slug
              title
              content
              image {
                data {
                  id
                  attributes {
                    url
                  }
                }
              }
              category {
                data {
                  id
                  attributes {
                    slug
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
