query Pages($slug: String) {
  pages(filters: { slug: { eq: $slug } }) {
    data {
      id
      attributes {
        slug
        title
        content
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
