query {
  pages {
    data {
      id
      attributes {
        slug
        title
        content
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
