query Pages($id: ID) {
  intros(filters: { id: { eq: $id } }) {
    data {
      id
      attributes {
        title
        content
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
