query {
  intros {
    data {
      id
      attributes {
        title
        content
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
